name: mypy
on: [pull_request, push]
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install mypy
      - run: pip install discord.py python-dotenv jishaku pillow cbvx tortoise-orm matplotlib numpy sympy
      - run: mkdir --parents --verbose .mypy_cache
      - run: mypy --ignore-missing-imports --install-types --non-interactive . || true